# Generated by Django 3.1.4 on 2020-12-21 19:23

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="maps_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="place_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="employment",
            name="timespan",
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
    ]
