---
- name: "This playbook configures server and deploys bonobo"
  hosts: all
  user: deployer
  become: yes
  roles:
    - nekeal.users
    - nekeal.postgresql_db
    - nekeal.nginx
    - nekeal.certbot
    - nekeal.docker_app
  
